### PR TITLE
Revisit common properties used in Layer1 configuration

### PR DESCRIPTION
**Pull request by ashutshkumr**
Changes proposed below can be visualized in the [data model tree](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/open-traffic-generator/models/opt-layer1/artifacts/openapi.yaml#tag/Configuration/operation/set_config).

1. Added documentation to emphasize on the fact that layer1 settings are not portable
2. Removed default from speed
3. Documented behavior for missing values in certain commonly used properties
4. Marked `auto_negotiate` and `ieee_media_defaults` as `under-review`

### CODE REVIEW

**Review by ajbalogh — APPROVED** [review]
lgtm

**Review by bortok — APPROVED** [review]

**Review by lyle-thompson-keysight — APPROVED** [review]
LGTM

**Review by apratimmukherjee — APPROVED** [review]

**Review by PrasenjitAdhikary — APPROVED** [review]
LGTM

**Comment by parthpower** [comment]
LGTM 👍

**Review by parthpower — APPROVED** [review]

**Pull request merged**
