### PR TITLE
Proposed LAG model

### PR DESCRIPTION
**Pull request by ajbalogh**
image

### CODE REVIEW

**Review by winstonliu1111 — COMMENTED** [review]
what is the meaning of the yellow vs. the green colored text in the diagram associated with this PR?

**Comment by ajbalogh** [comment]
The colors indicate relationships - yellow indicates that port.name is used in lag.port_names, the green lag.name is used in the PortTxRx.tx_port_name which is used in the Flow.tx_rx.

The x-constraint should be updated on the PorTxRx to include the Lag.properties.name

**Comment by ankur-sheth** [comment]
@ajbalogh I'm not that familiar with LAGs and how it is supposed to work.  Do we have a use-case and a script (as per this model) demonstrating the use-case?  Will make it easier for me to understand.

**Comment by ajbalogh** [comment]
sample code for lag flows

```python
# setup tx and rx ports
tx_port1 = Port(name='tx1')
tx_port2 = Port(name='tx2')
rx_port3 = Port(name='rx1')

# setup a lag of tx ports
lag = Lag(name='lag1', port_names=[tx_port1.name, tx_port2.name])
lacp = Lacp(actor_key=Pattern('1'))
lag.protocol = Protocol(choice='lacp', lacp=Lacp())
lag.ethernet = Ethernet(name='lag eth1',
                        src=Pattern(
                            Counter(start='000000000001',
                                    step='000000000001',
                                    up=True)))

# flow over the lag
port_endpoint = PortTxRx(tx_port_name=lag.name, rx_port_names=[rx_port3.name])
flow1 = Flow(name='lag flow 1', tx_rx=TxRx(port_endpoint))

# flow over the lag devices
tx_devices = Device(name='tx devices', container_name=lag.name, ipv4=Ipv4())
rx_devices = Device(name='rx devices',
                    container_name=rx_port3.name,
                    ipv4=Ipv4())
device_endpoint = DeviceTxRx(tx_device_names=[tx_devices.name],
                             rx_device_names=[rx_devices.name])
flow2 = Flow('lag flow 2', tx_rx=TxRx(device_endpoint))

# add everything to a config
config = Config(ports=[tx_port.name, tx_port2.name, rx_port.name],
                lags=[lag],
                devices=[tx_devices, rx_devices],
                flows=[flow1, flow2])

```

**Pull request merged**
